-- SB08 step 2: two tables, matching the Carrier and Bid entities.
--   carriers: id (identity primary key), name VARCHAR(255) not null AND unique, max_weight_kg INTEGER not null
--   bids:     id (identity primary key),
--             load_id    BIGINT not null, a FOREIGN KEY referencing loads(id)
--             carrier_id BIGINT not null, a FOREIGN KEY referencing carriers(id)
--             amount_pence BIGINT not null, status VARCHAR(20) not null,
--             placed_at TIMESTAMP(6) WITH TIME ZONE not null      (an Instant)
--   Name your constraints (CONSTRAINT fk_bids_load FOREIGN KEY ...) so error messages are readable.
--   Also create an INDEX on bids(load_id): "all bids for load 7" is the most common query, and a foreign key
--   column doesn't get an index automatically in PostgreSQL.
CREATE TABLE carriers
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    max_weight_kg INTEGER      NOT NULL,
    CONSTRAINT uk_carriers_name UNIQUE (name)
);

CREATE TABLE bids
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_id      BIGINT                      NOT NULL,
    carrier_id   BIGINT                      NOT NULL,
    amount_pence BIGINT                      NOT NULL,
    status       VARCHAR(20)                 NOT NULL,
    placed_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_bids_load FOREIGN KEY (load_id) REFERENCES loads (id),
    CONSTRAINT fk_bids_carrier FOREIGN KEY (carrier_id) REFERENCES carriers (id)
);

CREATE INDEX idx_bids_load_id ON bids (load_id);
