package com.freightboard.loads;


import java.time.LocalDate;

/**
 * SB06: Load is now a JPA ENTITY, a class whose objects are rows in the "loads" table.
 * Entities can't be records: JPA needs a no-argument constructor, and it changes fields after construction
 * (for example to set the generated id). The API now returns LoadResponse (a record) instead.
 *
 * TODO 1: map this class to the database with annotations:
 *   - it's an entity, stored in the table "loads"
 *   - id is the primary key, generated by the database (strategy IDENTITY)
 *   - origin, destination, weightKg, pickupDate, status: NOT NULL columns
 *   - status is stored as its NAME ("OPEN"), not its position (0), so reordering the enum can't corrupt data
 */
public class Load {

    private Long id;

    private String origin;

    private String destination;

    private int weightKg;

    private LocalDate pickupDate;

    private LoadStatus status;

    /** For JPA only. It creates the object first, then fills in the fields from the row. */
    protected Load() {
    }

    /** A new, unsaved load. The id stays null until the database assigns one. */
    public Load(LoadRequest request) {
        updateDetails(request);
        this.status = LoadStatus.OPEN;
    }

    public void updateDetails(LoadRequest request) {
        this.origin = request.origin();
        this.destination = request.destination();
        this.weightKg = request.weightKg();
        this.pickupDate = request.pickupDate();
    }

    public void cancel() {
        this.status = LoadStatus.CANCELLED;
    }

    public Long getId() {
        return id;
    }

    public String getOrigin() {
        return origin;
    }

    public String getDestination() {
        return destination;
    }

    public int getWeightKg() {
        return weightKg;
    }

    public LocalDate getPickupDate() {
        return pickupDate;
    }

    public LoadStatus getStatus() {
        return status;
    }

    @Override
    public String toString() {
        return "Load[id=" + id + ", " + origin + " -> " + destination + ", " + weightKg + " kg, " + pickupDate + ", " + status + "]";
    }
}
